[package]
name = "memset-nt"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
cfg-if = "1.0.0"

[workspace]
members = ["fuzz"]

[dev-dependencies]
criterion = "0.5.0"

[[bench]]
name = "bench"
harness = false

[features]
nightly = []
